### ISSUE TITLE
Crash in LocationService

### ISSUE THREAD

**Issue by evant** [chartbeat-labs/android_sdk#18]
```
08-03 09:33:54.580: E/AndroidRuntime(19776): java.lang.NullPointerException: Attempt to invoke virtual method 'int android.content.Context.checkCallingOrSelfPermission(java.lang.String)' on a null object reference
08-03 09:33:54.580: E/AndroidRuntime(19776):     at com.chartbeat.androidsdk.LocationService.isLocationPermissionEnabled(Unknown Source:2)
08-03 09:33:54.580: E/AndroidRuntime(19776):     at com.chartbeat.androidsdk.LocationService.updateLocation(Unknown Source:0)
08-03 09:33:54.580: E/AndroidRuntime(19776):     at com.chartbeat.androidsdk.ChartBeatTracker.updateLocation(Unknown Source:11)
08-03 09:33:54.580: E/AndroidRuntime(19776):     at com.chartbeat.androidsdk.ChartBeatTracker.trackNewView(Unknown Source:149)
08-03 09:33:54.580: E/AndroidRuntime(19776):     at com.chartbeat.androidsdk.ChartBeatTracker.trackViewImpl(Unknown Source:26)
08-03 09:33:54.580: E/AndroidRuntime(19776):     at com.chartbeat.androidsdk.ChartbeatServiceHandler.trackView(Unknown Source:39)
08-03 09:33:54.580: E/AndroidRuntime(19776):     at com.chartbeat.androidsdk.ChartbeatServiceHandler.handleMessageType(Unknown Source:172)
08-03 09:33:54.580: E/AndroidRuntime(19776):     at com.chartbeat.androidsdk.ChartbeatServiceHandler.processMessage(Unknown Source:26)
08-03 09:33:54.580: E/AndroidRuntime(19776):     at com.chartbeat.androidsdk.ChartbeatServiceHandler.handleMessage(Unknown Source:4)
08-03 09:33:54.580: E/AndroidRuntime(19776):     at android.os.Handler.dispatchMessage(Handler.java:105)
08-03 09:33:54.580: E/AndroidRuntime(19776):     at android.os.Looper.loop(Looper.java:164)
08-03 09:33:54.580: E/AndroidRuntime(19776):     at android.os.HandlerThread.run(HandlerThread.java:65)
```

It looks like it holds a `WeakReference` to the context but never checks if it's been cleaned up. As this is a service context, I'm curious why it's a `WeakReference` anyway.

**Comment by visiolink-android-dev** [comment]
We are seeing the same thing.

**Comment by deblaz** [comment]
Same thing here. Is anyone reading issues ?

**Comment by heavi5ide** [comment]
Hi, yes, we're looking into this and expect to be testing a solution by next week. Apologies for lack of communication here -- we don't really use Github issues internally (and I have notifications for watched repositories turned off to avoid a flood of emails), so we have been tracking this in our separate support ticketing system. I'll try to monitor the issues on this repo better moving forward.

**Comment by PeteSesto** [comment]
@heavi5ide Has this been resolved?  If so, which sdk version?

**Comment by emilyingram** [comment]
Hey Pete - I saw you'd also reached out to our Support team on Twitter, but to echo what they'd mentioned: Yes, this was resolved in v1.3.5, and you can feel free to jump to the latest version of v1.3.7 since there are no major changes.

If you have other questions, don't hesitate to reach out to support@chartbeat.com, which is the fastest way for us to get you answers. Thanks!

**Comment by PeteSesto** [comment]
Thank you for the reply!

Yeah, that was me. We're nearing release and I was looking for the quickest possible response so our QA team could have as much time with it as possible.

I appreciate all of the help,

Pete Sesto
Senior Mobile Engineer
NBC Owned Television Stations
O: 212-413-6323<tel:212-413-6323>
M: 347-803-6291<tel:347-803-6291>
E: pete.sesto@nbcuni.com<mailto:benjamin.sevilla@nbcuni.com>

[cid:2BFF66BA-316D-49FE-A522-CA980B468E03]


-------- Original message --------
