### ISSUE TITLE
RuntimeException Android Oreo

### ISSUE THREAD

**Issue by timrijckaert** [chartbeat-labs/android_sdk#19]
Hiya.

We are experiencing problems with the SDK on Android Oreo.

`08-27 14:32:48.420 26294-26294/com.foo.bar.application.debug E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                        Process: com.foo.bar.application.debug, PID: 26294
                                                                                        java.lang.RuntimeException: Unable to create service com.chartbeat.androidsdk.ChartbeatService: java.lang.NullPointerException: Attempt to read from field 'android.os.MessageQueue android.os.Looper.mQueue' on a null object reference
                                                                                            at android.app.ActivityThread.handleCreateService(ActivityThread.java:3414)
                                                                                            at android.app.ActivityThread.-wrap4(Unknown Source:0)
                                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1683)
                                                                                            at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                                            at android.os.Looper.loop(Looper.java:164)
                                                                                            at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                                            at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
                                                                                         Caused by: java.lang.NullPointerException: Attempt to read from field 'android.os.MessageQueue android.os.Looper.mQueue' on a null object reference
                                                                                            at android.os.Handler.<init>(Handler.java:232)
                                                                                            at android.os.Handler.<init>(Handler.java:140)
                                                                                            at com.chartbeat.androidsdk.ChartbeatServiceHandler.<init>(Unknown Source:0)
                                                                                            at com.chartbeat.androidsdk.ChartbeatService.onCreate(Unknown Source:37)
                                                                                            at android.app.ActivityThread.handleCreateService(ActivityThread.java:3404)
                                                                                            at android.app.ActivityThread.-wrap4(Unknown Source:0) 
                                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1683) 
                                                                                            at android.os.Handler.dispatchMessage(Handler.java:105) 
                                                                                            at android.os.Looper.loop(Looper.java:164) 
                                                                                            at android.app.ActivityThread.main(ActivityThread.java:6541) 
                                                                                            at java.lang.reflect.Method.invoke(Native Method)`

**Comment by heavi5ide** [comment]
Hi, thanks for reporting this! We are looking into Oreo issues and hope to have a new version soon that addresses these.
