### ISSUE TITLE
Background services limits in Oreo

### ISSUE THREAD

**Issue by visiolink-android-dev** [chartbeat-labs/android_sdk#20]
Our app is build with targetSdkVersion 26 and is restricted by Oreo's background services limits:
https://developer.android.com/about/versions/oreo/background.html#services

So to push the limits, I kept the Chartbeat tracker running (didn't call stopTracker) while the app was in the background.
When Android kills the ChartbeatService due to the limit from the link above, then the service starts to output the following every 15 seconds:
```
09-19 14:11:04.761 17679-17804/com.visiolink.reader.wrapper W/MessageQueue: Handler (android.os.Handler) {e3921fa} sending message to a Handler on a dead thread
                                                                            java.lang.IllegalStateException: Handler (android.os.Handler) {e3921fa} sending message to a Handler on a dead thread
                                                                                at android.os.MessageQueue.enqueueMessage(MessageQueue.java:545)
                                                                                at android.os.Handler.enqueueMessage(Handler.java:661)
                                                                                at android.os.Handler.sendMessageAtTime(Handler.java:630)
                                                                                at android.os.Handler.sendMessageDelayed(Handler.java:600)
                                                                                at android.os.Handler.post(Handler.java:356)
                                                                                at com.chartbeat.androidsdk.PingManager$1.onNext(PingManager.java:66)
                                                                                at rx.internal.util.ObserverSubscriber.onNext(ObserverSubscriber.java:34)
                                                                                at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
                                                                                at rx.internal.operators.OperatorFilter$FilterSubscriber.onNext(OperatorFilter.java:73)
                                                                                at rx.internal.operators.OperatorFilter$FilterSubscriber.onNext(OperatorFilter.java:73)
                                                                                at rx.internal.operators.OnSubscribeTimerPeriodically$1.call(OnSubscribeTimerPeriodically.java:52)
                                                                                at rx.Scheduler$Worker$1.call(Scheduler.java:134)
                                                                                at rx.internal.schedulers.EventLoopsScheduler$EventLoopWorker$2.call(EventLoopsScheduler.java:186)
                                                                                at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
                                                                                at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
                                                                                at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                                                                                at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
                                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                                                at java.lang.Thread.run(Thread.java:764)
``` 

And if the Tracker is then called (e.g Tracker.userInteracted()), then it will crash as it is no longer allowed to start the service from the background:

`09-19 14:16:26.019 17679-18654/com.visiolink.reader.wrapper E/ChartbeatTracker: Not allowed to start service Intent { cmp=com.visiolink.reader.wrapper/com.chartbeat.androidsdk.ChartbeatService (has extras) }: app is in background uid UidRecord{7b34df3 u0a280 LAST bg:+1m53s468ms idle procs:1 seq(0,0,0)}
                                                                                java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.visiolink.reader.wrapper/com.chartbeat.androidsdk.ChartbeatService (has extras) }: app is in background uid UidRecord{7b34df3 u0a280 LAST bg:+1m53s468ms idle procs:1 seq(0,0,0)}
                                                                                    at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1505)
                                                                                    at android.app.ContextImpl.startService(ContextImpl.java:1461)
                                                                                    at android.content.ContextWrapper.startService(ContextWrapper.java:644)
                                                                                    at com.chartbeat.androidsdk.Tracker.trackView(Tracker.java:204)
                                                                                    at com.visiolink.reader.ChartbeatTracker.trackArticleReadingStart(ChartbeatTracker.java:42)
                                                                                    at com.visiolink.reader.utilities.TrackingUtilities$1.doInBackground(TrackingUtilities.java:107)
                                                                                    at com.visiolink.reader.utilities.TrackingUtilities$1.doInBackground(TrackingUtilities.java:101)
                                                                                    at android.os.AsyncTask$2.call(AsyncTask.java:333)
                                                                                    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                                                                                    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
                                                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                                                    at java.lang.Thread.run(Thread.java:764)`

The tracker should handle this scenario in Oreo more gracefully.

**Comment by visiolink-android-dev** [comment]
I think this is also the root cause of #18 and #19

**Comment by heavi5ide** [comment]
Hi, thanks for reporting this, and for the high level of detail! Much appreciated. We are looking into Oreo issues this week and hope to have a new version out soon that addresses these.

**Comment by timrijckaert** [comment]
Any news on this?

**Comment by plonsker** [comment]
Our engineers are currently reviewing a PR that should resolve the issue. We will update this ticket once the changes have been fully audited and approved.

**Comment by timrijckaert** [comment]
2 months for one bug fix. 
Let's not forget we are paying for this service.

Nice, ...

**Comment by joshschwartz** [comment]
Hey Tim, I totally understand your frustration and apologize for the delay. We've had a couple of major releases in other parts of our product over the past couple of months and it's caused us to be slower than we'd like in triaging these issues. We don't expect to have similar delays in the future, but that doesn't mean this delay is cool. If you drop me your address at josh@chartbeat.com we'll send you and the team something as a token of our thanks for your patience.

**Comment by timrijckaert** [comment]
I think you should send this to my superior.
Hanne.BRASSEUR@VRT.BE

**Comment by rayzhouzhj** [comment]
@joshschwartz 
Regarding to this commit, could you confirm if it's already been resolved?
https://github.com/chartbeat-labs/android_sdk/commit/befaf99a0e73fca86a99900c7d30364bd31f64d4

**Comment by heavi5ide** [comment]
@rayzhouzhj We have a partner beta testing this currently. Once testing is complete, we will release a new version to bintray. I'll follow up here at that point as well.

**Comment by timrijckaert** [comment]
.... 14 days have past

**Comment by plonsker** [comment]
@timrijckaert the fix is still currently being tested by select partners.

**Comment by plonsker** [comment]
@timrijckaert fix is currently being tested by select partners. We have reached out to confirm if there are any outstanding issues.

**Comment by plonsker** [comment]
@timrijckaert Our test partner has confirmed that the issue have been resolved in the latest version.

**Comment by timrijckaert** [comment]
Can you up the version to `1..3.5` if it is out of beta status?

**Comment by plonsker** [comment]
@timrijckaert yes, we will be updating the version to 1.3.5 and will reach out via email once it is ready to be deployed.

**Comment by timrijckaert** [comment]
Seems like your QA failed to find this one.
Let your developer read up about background services and how to schedule them properly on Android 8 please.
Our QA team should not find bugs in your code multiple times.

Android 8.1
Nexus 5X

Scenario: App kill and wait two seconds.
```
Fatal Exception: java.lang.RuntimeException: Unable to stop service com.chartbeat.androidsdk.ChartbeatService@7475a3: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.chartbeat.androidsdk.ChartBeatTracker.stopTracker()' on a null object reference
       at android.app.ActivityThread.handleStopService(ActivityThread.java:3522)
       at android.app.ActivityThread.-wrap26(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1697)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'void com.chartbeat.androidsdk.ChartBeatTracker.stopTracker()' on a null object reference
       at com.chartbeat.androidsdk.ChartbeatServiceHandler.pauseTracker(Unknown Source:2)
       at com.chartbeat.androidsdk.ChartbeatService.onDestroy(Unknown Source:8)
       at android.app.ActivityThread.handleStopService(ActivityThread.java:3504)
       at android.app.ActivityThread.-wrap26(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1697)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by joststricker** [comment]
Any idea when 1.3.5 will be moved out of beta?

**Comment by plonsker** [comment]
@timrijckaert @joststricker v1.3.5, which fixes the crashes that you were experiencing, has been deployed to prod. We are actively looking at how we can change our SDK functionality to eliminate the issue with persistent background services, but we didn't want to wait for the broader change before shipping the crash fixes.
